spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chattypostgres
    username: dwth0mas
    password: Pa5tl1fechatty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt-secret: 6B58703273357638792F423F4528482B4D6251655468576D5A7133743677397A